# Generated from ./lib/postgrex/pg_output/types.json at 2022-11-02 08:47:23Z

[
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "boolin",
    oid: 16,
    output: "boolout",
    receive: "boolrecv",
    send: "boolsend",
    type: "bool"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "byteain",
    oid: 17,
    output: "byteaout",
    receive: "bytearecv",
    send: "byteasend",
    type: "bytea"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "charin",
    oid: 18,
    output: "charout",
    receive: "charrecv",
    send: "charsend",
    type: "char"
  },
  %{
    array_elem: 18,
    base_type: 0,
    comp_elems: [],
    input: "namein",
    oid: 19,
    output: "nameout",
    receive: "namerecv",
    send: "namesend",
    type: "name"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "int8in",
    oid: 20,
    output: "int8out",
    receive: "int8recv",
    send: "int8send",
    type: "int8"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "int2in",
    oid: 21,
    output: "int2out",
    receive: "int2recv",
    send: "int2send",
    type: "int2"
  },
  %{
    array_elem: 21,
    base_type: 0,
    comp_elems: [],
    input: "int2vectorin",
    oid: 22,
    output: "int2vectorout",
    receive: "int2vectorrecv",
    send: "int2vectorsend",
    type: "int2vector"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "int4in",
    oid: 23,
    output: "int4out",
    receive: "int4recv",
    send: "int4send",
    type: "int4"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "regprocin",
    oid: 24,
    output: "regprocout",
    receive: "regprocrecv",
    send: "regprocsend",
    type: "regproc"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "textin",
    oid: 25,
    output: "textout",
    receive: "textrecv",
    send: "textsend",
    type: "text"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "oidin",
    oid: 26,
    output: "oidout",
    receive: "oidrecv",
    send: "oidsend",
    type: "oid"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "tidin",
    oid: 27,
    output: "tidout",
    receive: "tidrecv",
    send: "tidsend",
    type: "tid"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "xidin",
    oid: 28,
    output: "xidout",
    receive: "xidrecv",
    send: "xidsend",
    type: "xid"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "cidin",
    oid: 29,
    output: "cidout",
    receive: "cidrecv",
    send: "cidsend",
    type: "cid"
  },
  %{
    array_elem: 26,
    base_type: 0,
    comp_elems: [],
    input: "oidvectorin",
    oid: 30,
    output: "oidvectorout",
    receive: "oidvectorrecv",
    send: "oidvectorsend",
    type: "oidvector"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "json_in",
    oid: 114,
    output: "json_out",
    receive: "json_recv",
    send: "json_send",
    type: "json"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "xml_in",
    oid: 142,
    output: "xml_out",
    receive: "xml_recv",
    send: "xml_send",
    type: "xml"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "pg_node_tree_in",
    oid: 194,
    output: "pg_node_tree_out",
    receive: "pg_node_tree_recv",
    send: "pg_node_tree_send",
    type: "pg_node_tree"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "pg_ndistinct_in",
    oid: 3361,
    output: "pg_ndistinct_out",
    receive: "pg_ndistinct_recv",
    send: "pg_ndistinct_send",
    type: "pg_ndistinct"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "pg_dependencies_in",
    oid: 3402,
    output: "pg_dependencies_out",
    receive: "pg_dependencies_recv",
    send: "pg_dependencies_send",
    type: "pg_dependencies"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "pg_mcv_list_in",
    oid: 5017,
    output: "pg_mcv_list_out",
    receive: "pg_mcv_list_recv",
    send: "pg_mcv_list_send",
    type: "pg_mcv_list"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "pg_ddl_command_in",
    oid: 32,
    output: "pg_ddl_command_out",
    receive: "pg_ddl_command_recv",
    send: "pg_ddl_command_send",
    type: "pg_ddl_command"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "xid8in",
    oid: 5069,
    output: "xid8out",
    receive: "xid8recv",
    send: "xid8send",
    type: "xid8"
  },
  %{
    array_elem: 701,
    base_type: 0,
    comp_elems: [],
    input: "point_in",
    oid: 600,
    output: "point_out",
    receive: "point_recv",
    send: "point_send",
    type: "point"
  },
  %{
    array_elem: 600,
    base_type: 0,
    comp_elems: [],
    input: "lseg_in",
    oid: 601,
    output: "lseg_out",
    receive: "lseg_recv",
    send: "lseg_send",
    type: "lseg"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "path_in",
    oid: 602,
    output: "path_out",
    receive: "path_recv",
    send: "path_send",
    type: "path"
  },
  %{
    array_elem: 600,
    base_type: 0,
    comp_elems: [],
    input: "box_in",
    oid: 603,
    output: "box_out",
    receive: "box_recv",
    send: "box_send",
    type: "box"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "poly_in",
    oid: 604,
    output: "poly_out",
    receive: "poly_recv",
    send: "poly_send",
    type: "polygon"
  },
  %{
    array_elem: 701,
    base_type: 0,
    comp_elems: [],
    input: "line_in",
    oid: 628,
    output: "line_out",
    receive: "line_recv",
    send: "line_send",
    type: "line"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "float4in",
    oid: 700,
    output: "float4out",
    receive: "float4recv",
    send: "float4send",
    type: "float4"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "float8in",
    oid: 701,
    output: "float8out",
    receive: "float8recv",
    send: "float8send",
    type: "float8"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "unknownin",
    oid: 705,
    output: "unknownout",
    receive: "unknownrecv",
    send: "unknownsend",
    type: "unknown"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "circle_in",
    oid: 718,
    output: "circle_out",
    receive: "circle_recv",
    send: "circle_send",
    type: "circle"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "cash_in",
    oid: 790,
    output: "cash_out",
    receive: "cash_recv",
    send: "cash_send",
    type: "money"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "macaddr_in",
    oid: 829,
    output: "macaddr_out",
    receive: "macaddr_recv",
    send: "macaddr_send",
    type: "macaddr"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "inet_in",
    oid: 869,
    output: "inet_out",
    receive: "inet_recv",
    send: "inet_send",
    type: "inet"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "cidr_in",
    oid: 650,
    output: "cidr_out",
    receive: "cidr_recv",
    send: "cidr_send",
    type: "cidr"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "macaddr8_in",
    oid: 774,
    output: "macaddr8_out",
    receive: "macaddr8_recv",
    send: "macaddr8_send",
    type: "macaddr8"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "aclitemin",
    oid: 1033,
    output: "aclitemout",
    receive: "-",
    send: "-",
    type: "aclitem"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "bpcharin",
    oid: 1042,
    output: "bpcharout",
    receive: "bpcharrecv",
    send: "bpcharsend",
    type: "bpchar"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "varcharin",
    oid: 1043,
    output: "varcharout",
    receive: "varcharrecv",
    send: "varcharsend",
    type: "varchar"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "date_in",
    oid: 1082,
    output: "date_out",
    receive: "date_recv",
    send: "date_send",
    type: "date"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "time_in",
    oid: 1083,
    output: "time_out",
    receive: "time_recv",
    send: "time_send",
    type: "time"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "timestamp_in",
    oid: 1114,
    output: "timestamp_out",
    receive: "timestamp_recv",
    send: "timestamp_send",
    type: "timestamp"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "timestamptz_in",
    oid: 1184,
    output: "timestamptz_out",
    receive: "timestamptz_recv",
    send: "timestamptz_send",
    type: "timestamptz"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "interval_in",
    oid: 1186,
    output: "interval_out",
    receive: "interval_recv",
    send: "interval_send",
    type: "interval"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "timetz_in",
    oid: 1266,
    output: "timetz_out",
    receive: "timetz_recv",
    send: "timetz_send",
    type: "timetz"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "bit_in",
    oid: 1560,
    output: "bit_out",
    receive: "bit_recv",
    send: "bit_send",
    type: "bit"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "varbit_in",
    oid: 1562,
    output: "varbit_out",
    receive: "varbit_recv",
    send: "varbit_send",
    type: "varbit"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "numeric_in",
    oid: 1700,
    output: "numeric_out",
    receive: "numeric_recv",
    send: "numeric_send",
    type: "numeric"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "textin",
    oid: 1790,
    output: "textout",
    receive: "textrecv",
    send: "textsend",
    type: "refcursor"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "regprocedurein",
    oid: 2202,
    output: "regprocedureout",
    receive: "regprocedurerecv",
    send: "regproceduresend",
    type: "regprocedure"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "regoperin",
    oid: 2203,
    output: "regoperout",
    receive: "regoperrecv",
    send: "regopersend",
    type: "regoper"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "regoperatorin",
    oid: 2204,
    output: "regoperatorout",
    receive: "regoperatorrecv",
    send: "regoperatorsend",
    type: "regoperator"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "regclassin",
    oid: 2205,
    output: "regclassout",
    receive: "regclassrecv",
    send: "regclasssend",
    type: "regclass"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "regcollationin",
    oid: 4191,
    output: "regcollationout",
    receive: "regcollationrecv",
    send: "regcollationsend",
    type: "regcollation"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "regtypein",
    oid: 2206,
    output: "regtypeout",
    receive: "regtyperecv",
    send: "regtypesend",
    type: "regtype"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "regrolein",
    oid: 4096,
    output: "regroleout",
    receive: "regrolerecv",
    send: "regrolesend",
    type: "regrole"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "regnamespacein",
    oid: 4089,
    output: "regnamespaceout",
    receive: "regnamespacerecv",
    send: "regnamespacesend",
    type: "regnamespace"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "uuid_in",
    oid: 2950,
    output: "uuid_out",
    receive: "uuid_recv",
    send: "uuid_send",
    type: "uuid"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "pg_lsn_in",
    oid: 3220,
    output: "pg_lsn_out",
    receive: "pg_lsn_recv",
    send: "pg_lsn_send",
    type: "pg_lsn"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "tsvectorin",
    oid: 3614,
    output: "tsvectorout",
    receive: "tsvectorrecv",
    send: "tsvectorsend",
    type: "tsvector"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "gtsvectorin",
    oid: 3642,
    output: "gtsvectorout",
    receive: "-",
    send: "-",
    type: "gtsvector"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "tsqueryin",
    oid: 3615,
    output: "tsqueryout",
    receive: "tsqueryrecv",
    send: "tsquerysend",
    type: "tsquery"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "regconfigin",
    oid: 3734,
    output: "regconfigout",
    receive: "regconfigrecv",
    send: "regconfigsend",
    type: "regconfig"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "regdictionaryin",
    oid: 3769,
    output: "regdictionaryout",
    receive: "regdictionaryrecv",
    send: "regdictionarysend",
    type: "regdictionary"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "jsonb_in",
    oid: 3802,
    output: "jsonb_out",
    receive: "jsonb_recv",
    send: "jsonb_send",
    type: "jsonb"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "jsonpath_in",
    oid: 4072,
    output: "jsonpath_out",
    receive: "jsonpath_recv",
    send: "jsonpath_send",
    type: "jsonpath"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "txid_snapshot_in",
    oid: 2970,
    output: "txid_snapshot_out",
    receive: "txid_snapshot_recv",
    send: "txid_snapshot_send",
    type: "txid_snapshot"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "pg_snapshot_in",
    oid: 5038,
    output: "pg_snapshot_out",
    receive: "pg_snapshot_recv",
    send: "pg_snapshot_send",
    type: "pg_snapshot"
  },
  %{
    array_elem: 0,
    base_type: 23,
    comp_elems: [],
    input: "range_in",
    oid: 3904,
    output: "range_out",
    receive: "range_recv",
    send: "range_send",
    type: "int4range"
  },
  %{
    array_elem: 0,
    base_type: 1700,
    comp_elems: [],
    input: "range_in",
    oid: 3906,
    output: "range_out",
    receive: "range_recv",
    send: "range_send",
    type: "numrange"
  },
  %{
    array_elem: 0,
    base_type: 1114,
    comp_elems: [],
    input: "range_in",
    oid: 3908,
    output: "range_out",
    receive: "range_recv",
    send: "range_send",
    type: "tsrange"
  },
  %{
    array_elem: 0,
    base_type: 1184,
    comp_elems: [],
    input: "range_in",
    oid: 3910,
    output: "range_out",
    receive: "range_recv",
    send: "range_send",
    type: "tstzrange"
  },
  %{
    array_elem: 0,
    base_type: 1082,
    comp_elems: [],
    input: "range_in",
    oid: 3912,
    output: "range_out",
    receive: "range_recv",
    send: "range_send",
    type: "daterange"
  },
  %{
    array_elem: 0,
    base_type: 20,
    comp_elems: [],
    input: "range_in",
    oid: 3926,
    output: "range_out",
    receive: "range_recv",
    send: "range_send",
    type: "int8range"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "record_in",
    oid: 2249,
    output: "record_out",
    receive: "record_recv",
    send: "record_send",
    type: "record"
  },
  %{
    array_elem: 2249,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 2287,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_record"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "cstring_in",
    oid: 2275,
    output: "cstring_out",
    receive: "cstring_recv",
    send: "cstring_send",
    type: "cstring"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "any_in",
    oid: 2276,
    output: "any_out",
    receive: "-",
    send: "-",
    type: "any"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "anyarray_in",
    oid: 2277,
    output: "anyarray_out",
    receive: "anyarray_recv",
    send: "anyarray_send",
    type: "anyarray"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "void_in",
    oid: 2278,
    output: "void_out",
    receive: "void_recv",
    send: "void_send",
    type: "void"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "trigger_in",
    oid: 2279,
    output: "trigger_out",
    receive: "-",
    send: "-",
    type: "trigger"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "event_trigger_in",
    oid: 3838,
    output: "event_trigger_out",
    receive: "-",
    send: "-",
    type: "event_trigger"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "language_handler_in",
    oid: 2280,
    output: "language_handler_out",
    receive: "-",
    send: "-",
    type: "language_handler"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "internal_in",
    oid: 2281,
    output: "internal_out",
    receive: "-",
    send: "-",
    type: "internal"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "anyelement_in",
    oid: 2283,
    output: "anyelement_out",
    receive: "-",
    send: "-",
    type: "anyelement"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "anynonarray_in",
    oid: 2776,
    output: "anynonarray_out",
    receive: "-",
    send: "-",
    type: "anynonarray"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "anyenum_in",
    oid: 3500,
    output: "anyenum_out",
    receive: "-",
    send: "-",
    type: "anyenum"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "fdw_handler_in",
    oid: 3115,
    output: "fdw_handler_out",
    receive: "-",
    send: "-",
    type: "fdw_handler"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "index_am_handler_in",
    oid: 325,
    output: "index_am_handler_out",
    receive: "-",
    send: "-",
    type: "index_am_handler"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "tsm_handler_in",
    oid: 3310,
    output: "tsm_handler_out",
    receive: "-",
    send: "-",
    type: "tsm_handler"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "table_am_handler_in",
    oid: 269,
    output: "table_am_handler_out",
    receive: "-",
    send: "-",
    type: "table_am_handler"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "anyrange_in",
    oid: 3831,
    output: "anyrange_out",
    receive: "-",
    send: "-",
    type: "anyrange"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "anycompatible_in",
    oid: 5077,
    output: "anycompatible_out",
    receive: "-",
    send: "-",
    type: "anycompatible"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "anycompatiblearray_in",
    oid: 5078,
    output: "anycompatiblearray_out",
    receive: "anycompatiblearray_recv",
    send: "anycompatiblearray_send",
    type: "anycompatiblearray"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "anycompatiblenonarray_in",
    oid: 5079,
    output: "anycompatiblenonarray_out",
    receive: "-",
    send: "-",
    type: "anycompatiblenonarray"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "anycompatiblerange_in",
    oid: 5080,
    output: "anycompatiblerange_out",
    receive: "-",
    send: "-",
    type: "anycompatiblerange"
  },
  %{
    array_elem: 16,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1000,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_bool"
  },
  %{
    array_elem: 17,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1001,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_bytea"
  },
  %{
    array_elem: 18,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1002,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_char"
  },
  %{
    array_elem: 19,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1003,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_name"
  },
  %{
    array_elem: 20,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1016,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_int8"
  },
  %{
    array_elem: 21,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1005,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_int2"
  },
  %{
    array_elem: 22,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1006,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_int2vector"
  },
  %{
    array_elem: 23,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1007,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_int4"
  },
  %{
    array_elem: 24,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1008,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_regproc"
  },
  %{
    array_elem: 25,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1009,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_text"
  },
  %{
    array_elem: 26,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1028,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_oid"
  },
  %{
    array_elem: 27,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1010,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_tid"
  },
  %{
    array_elem: 28,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1011,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_xid"
  },
  %{
    array_elem: 29,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1012,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_cid"
  },
  %{
    array_elem: 30,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1013,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_oidvector"
  },
  %{
    array_elem: 114,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 199,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_json"
  },
  %{
    array_elem: 142,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 143,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_xml"
  },
  %{
    array_elem: 5069,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 271,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_xid8"
  },
  %{
    array_elem: 600,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1017,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_point"
  },
  %{
    array_elem: 601,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1018,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_lseg"
  },
  %{
    array_elem: 602,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1019,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_path"
  },
  %{
    array_elem: 603,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1020,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_box"
  },
  %{
    array_elem: 604,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1027,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_polygon"
  },
  %{
    array_elem: 628,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 629,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_line"
  },
  %{
    array_elem: 700,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1021,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_float4"
  },
  %{
    array_elem: 701,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1022,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_float8"
  },
  %{
    array_elem: 718,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 719,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_circle"
  },
  %{
    array_elem: 790,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 791,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_money"
  },
  %{
    array_elem: 829,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1040,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_macaddr"
  },
  %{
    array_elem: 869,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1041,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_inet"
  },
  %{
    array_elem: 650,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 651,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_cidr"
  },
  %{
    array_elem: 774,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 775,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_macaddr8"
  },
  %{
    array_elem: 1033,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1034,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_aclitem"
  },
  %{
    array_elem: 1042,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1014,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_bpchar"
  },
  %{
    array_elem: 1043,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1015,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_varchar"
  },
  %{
    array_elem: 1082,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1182,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_date"
  },
  %{
    array_elem: 1083,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1183,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_time"
  },
  %{
    array_elem: 1114,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1115,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_timestamp"
  },
  %{
    array_elem: 1184,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1185,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_timestamptz"
  },
  %{
    array_elem: 1186,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1187,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_interval"
  },
  %{
    array_elem: 1266,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1270,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_timetz"
  },
  %{
    array_elem: 1560,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1561,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_bit"
  },
  %{
    array_elem: 1562,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1563,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_varbit"
  },
  %{
    array_elem: 1700,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1231,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_numeric"
  },
  %{
    array_elem: 1790,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 2201,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_refcursor"
  },
  %{
    array_elem: 2202,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 2207,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_regprocedure"
  },
  %{
    array_elem: 2203,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 2208,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_regoper"
  },
  %{
    array_elem: 2204,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 2209,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_regoperator"
  },
  %{
    array_elem: 2205,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 2210,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_regclass"
  },
  %{
    array_elem: 4191,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 4192,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_regcollation"
  },
  %{
    array_elem: 2206,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 2211,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_regtype"
  },
  %{
    array_elem: 4096,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 4097,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_regrole"
  },
  %{
    array_elem: 4089,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 4090,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_regnamespace"
  },
  %{
    array_elem: 2950,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 2951,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_uuid"
  },
  %{
    array_elem: 3220,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 3221,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_pg_lsn"
  },
  %{
    array_elem: 3614,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 3643,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_tsvector"
  },
  %{
    array_elem: 3642,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 3644,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_gtsvector"
  },
  %{
    array_elem: 3615,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 3645,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_tsquery"
  },
  %{
    array_elem: 3734,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 3735,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_regconfig"
  },
  %{
    array_elem: 3769,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 3770,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_regdictionary"
  },
  %{
    array_elem: 3802,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 3807,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_jsonb"
  },
  %{
    array_elem: 4072,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 4073,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_jsonpath"
  },
  %{
    array_elem: 2970,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 2949,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_txid_snapshot"
  },
  %{
    array_elem: 5038,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 5039,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_pg_snapshot"
  },
  %{
    array_elem: 3904,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 3905,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_int4range"
  },
  %{
    array_elem: 3906,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 3907,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_numrange"
  },
  %{
    array_elem: 3908,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 3909,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_tsrange"
  },
  %{
    array_elem: 3910,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 3911,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_tstzrange"
  },
  %{
    array_elem: 3912,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 3913,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_daterange"
  },
  %{
    array_elem: 3926,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 3927,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_int8range"
  },
  %{
    array_elem: 2275,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 1263,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_cstring"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "domain_in",
    oid: 13124,
    output: "int4out",
    receive: "domain_recv",
    send: "int4send",
    type: "cardinal_number"
  },
  %{
    array_elem: 13124,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 13123,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_cardinal_number"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "domain_in",
    oid: 13127,
    output: "varcharout",
    receive: "domain_recv",
    send: "varcharsend",
    type: "character_data"
  },
  %{
    array_elem: 13127,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 13126,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_character_data"
  },
  %{
    array_elem: 18,
    base_type: 0,
    comp_elems: [],
    input: "domain_in",
    oid: 13129,
    output: "nameout",
    receive: "domain_recv",
    send: "namesend",
    type: "sql_identifier"
  },
  %{
    array_elem: 13129,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 13128,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_sql_identifier"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "domain_in",
    oid: 13134,
    output: "timestamptz_out",
    receive: "domain_recv",
    send: "timestamptz_send",
    type: "time_stamp"
  },
  %{
    array_elem: 13134,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 13133,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_time_stamp"
  },
  %{
    array_elem: 0,
    base_type: 0,
    comp_elems: [],
    input: "domain_in",
    oid: 13136,
    output: "varcharout",
    receive: "domain_recv",
    send: "varcharsend",
    type: "yes_or_no"
  },
  %{
    array_elem: 13136,
    base_type: 0,
    comp_elems: [],
    input: "array_in",
    oid: 13135,
    output: "array_out",
    receive: "array_recv",
    send: "array_send",
    type: "_yes_or_no"
  }
]
